% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  11pt,
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{caption}
\usepackage{anyfontsize}
\raggedright
\hyphenpenalty=10000
\exhyphenpenalty=10000
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Online Appendix},
  pdfauthor={Jeffrey Stark},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Online Appendix}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Trust in Information and Pandemic Approval in Southeast Asia:
Evidence from the Vietnam Paradox}
\author{Jeffrey Stark}
\date{2026-02-28}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
}

\section{Appendix A: Survey Question
Wording}\label{sec-appendix-questions}

This appendix documents the exact wording of all Asian Barometer Wave 6
survey items used in our analysis. For each measure, we provide the
original question text, response options, and any coding notes relevant
to interpretation.

\subsection{A.1 Dependent Variable}\label{a.1-dependent-variable}

\textbf{Government Pandemic Handling} (q142)

\emph{Question:} ``How well or badly do you think the government handled
the pandemic?''

\emph{Response options:} (1) Very badly; (2) Badly; (3) Quite well; (4)
Very well

\emph{Coding:} Higher values indicate more favourable evaluations. This
item serves as the primary dependent variable throughout the analysis.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{A.2 Primary Independent
Variables}\label{a.2-primary-independent-variables}

\subsubsection{A.2.1 COVID-19 Infection}\label{a.2.1-covid-19-infection}

\textbf{Personal/Family COVID Infection} (q138)

\emph{Question:} ``Have you or your family members previously contracted
the COVID-19 virus?''

\emph{Response options:} (0) No; (1) Yes

\emph{Coding:} Binary indicator. Note that this item captures
household-level exposure rather than personal infection alone, which may
inflate prevalence estimates compared to individual-only measures.

\subsubsection{A.2.2 Trust in COVID
Information}\label{a.2.2-trust-in-covid-information}

\textbf{Trust in Government COVID Information} (q141)

\emph{Question:} ``How much do you trust the Covid-19 related
information provided by the government?''

\emph{Response options:} (1) No trust at all; (2) Not a lot of trust;
(3) Quite a lot of trust; (4) A great deal of trust

\emph{Coding:} Higher values indicate greater trust. This item serves as
the key mediating variable in our theoretical framework.

\subsubsection{A.2.3 Economic Impact}\label{a.2.3-economic-impact}

\textbf{COVID-19 Economic Impact} (q140)

\emph{Question:} ``Thinking of the negative impact of COVID-19 on your
family's livelihood, how serious is it in your view?''

\emph{Response options:} (1) Not much impact; (2) Some impact, but not
serious; (3) Serious impact; (4) Very serious impact

\emph{Coding:} Higher values indicate greater perceived economic
hardship from the pandemic.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{A.3 Institutional Trust
Index}\label{a.3-institutional-trust-index}

\textbf{Institutional Trust} (q7--q15)

\emph{Stem question:} ``I'm going to name a number of institutions. For
each one, please tell me how much trust do you have in them?''

\emph{Institutions:}

\begin{longtable}[]{@{}ll@{}}
\toprule\noalign{}
Item & Institution \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
q7 & National government \\
q8 & Courts \\
q9 & Police \\
q10 & Political parties \\
q11 & Parliament/National Assembly \\
q12 & Civil service \\
q13 & Military \\
q14 & Election commission \\
q15 & Local government \\
\end{longtable}

\emph{Response options (all items):} (1) None at all; (2) Not very much
trust; (3) Quite a lot of trust; (4) A great deal of trust

\emph{Index construction:} Mean of all nine items, standardised to a
1--4 scale. Higher values indicate greater institutional trust.
Cronbach's α \textgreater{} 0.90 across all three countries.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{A.4 Authoritarian Acceptance
Index}\label{a.4-authoritarian-acceptance-index}

\textbf{Authoritarian Governance Acceptance} (q168--q171)

\emph{Items:}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 2\tabcolsep) * \real{0.3529}}
  >{\raggedright\arraybackslash}p{(\linewidth - 2\tabcolsep) * \real{0.6471}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Item
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Statement
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
q168 & ``In order to solve the country's urgent problems, a leader can
govern the country by decrees and disregard the parliament if
necessary.'' \\
q169 & ``As long as a government can solve our country's economic
problem, it does not matter if the government holds regular elections or
not.'' \\
q170 & ``This country needs a leader who can break the rules if
necessary to get things done.'' \\
q171 & ``As long as the government can maintain order and stability in
the country, it does not matter whether it is democratic or
undemocratic.'' \\
\end{longtable}

\emph{Response options (all items):} (1) Strongly disagree; (2) Somewhat
disagree; (3) Somewhat agree; (4) Strongly agree

\emph{Index construction:} Mean of all four items. Higher values
indicate greater acceptance of authoritarian governance practices. Items
were originally coded such that agreement indicated authoritarian
acceptance; no reverse-coding was applied. Cronbach's α = 0.85.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{A.5 Democratic Attitudes}\label{a.5-democratic-attitudes}

\textbf{Satisfaction with Democracy} (q90)

\emph{Question:} ``On the whole, how satisfied or dissatisfied are you
with the way democracy works in {[}COUNTRY{]}?''

\emph{Response options:} (1) Not at all satisfied; (2) Not very
satisfied; (3) Fairly satisfied; (4) Very satisfied

\emph{Coding:} Higher values indicate greater satisfaction. This item is
used both as a control variable and as a falsification test outcome in
sensitivity analyses.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{A.6 Social Desirability
Check}\label{a.6-social-desirability-check}

\textbf{Freedom of Speech Perception} (q106)

\emph{Question:} ``People are free to speak what they think without
fear.''

\emph{Response options:} (1) Strongly disagree; (2) Somewhat disagree;
(3) Somewhat agree; (4) Strongly agree

\emph{Coding:} This item is used in the Discussion section to test
social desirability bias. Respondents who disagree (responses 1--2) are
coded as perceiving speech constraints, providing a subsample for
robustness checks.

\begin{longtable}[]{@{}lrrr@{}}

\caption{\label{tbl-social-desirability}Perceived Speech Constraints by
Country}

\tabularnewline

\toprule\noalign{}
Country & N & \% Constrained & \% Free \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Thailand & 1,120 & 22.5 & 77.5 \\
Vietnam & 1,203 & 40.3 & 59.7 \\
Cambodia & 1,184 & 28.7 & 71.3 \\

\end{longtable}

\emph{Descriptive Statistics:} The table above presents the percentage
of respondents who perceive constraints on free speech (disagree that
people are free to speak without fear). Vietnamese respondents report
substantially higher perceived constraints (40.3\%) compared to
Cambodian (28.7\%) and Thai (22.5\%) respondents. Alternatively, 59.7\%
of Vietnamese respondents perceive speech freedom (agree people are free
to speak), compared to only 71.3\% in Cambodia and 77.5\% in Thailand.
This paradox---higher perceived freedom in the more authoritarian
context---is referenced in the Discussion section's social desirability
analysis. The fact that Vietnamese respondents openly report substantial
speech constraints (alongside high infection rates) suggests responses
are not uniformly driven by fear.

\emph{Note:} ``Constrained'' = Disagree/Strongly disagree that ``people
are free to speak what they think without fear'' (freedom\_of\_speech ≤
2, reverse-coded from q106 ≥ 3). ``Free'' = Agree/Strongly agree
(freedom\_of\_speech ≥ 3, reverse-coded from q106 ≤ 2). Statistics from
validated dataset excluding missing values.

\emph{Social Desirability Test (Vietnam):} Even assuming social
desirability inflates reports of free speech, the 40.3\% of Vietnamese
respondents who openly disagreed that ``people are free to speak without
fear'' represent those least susceptible to such pressure. Yet their
approval of pandemic handling (97.5\%) is virtually identical to those
who report feeling free (97.3\%). If fear were driving responses, these
respondents---who already demonstrated willingness to offer ``risky''
answers---should show lower approval. They do not.

\begin{longtable}[]{@{}lr@{}}

\caption{\label{tbl-freedom-approval-correlation}Correlation Between
Freedom of Speech and Government Pandemic Approval (Vietnam)}

\tabularnewline

\toprule\noalign{}
Measure & Value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
N & 1,195 \\
Correlation (r) & 0.063 \\
95\% CI & {[}0.006, 0.119{]} \\
p-value & 0.030 \\
Mean Freedom of Speech & 2.70 \\
Mean Govt Approval & 3.61 \\

\end{longtable}

The table above presents the correlation between perceived speech
freedom and government pandemic approval. The correlation is positive
but substantively negligible (r = 0.063, p = 0.03), indicating that
perceptions of speech freedom have virtually no relationship with
approval ratings. This near-zero correlation further undermines the
social desirability explanation: if fear of reprisal drove both high
approval and reports of freedom, we would expect a much stronger
positive relationship.

\emph{Note:} Both variables are 4-point scales where higher values
indicate more agreement. Correlation uses Pearson's r with complete
cases only. The weak correlation (r \textless{} 0.10) indicates
perceived speech freedom explains less than 1\% of variance in approval
ratings.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{A.7 Economic Perceptions}\label{a.7-economic-perceptions}

\subsubsection{A.7.1 Sociotropic Evaluations (National
Economy)}\label{a.7.1-sociotropic-evaluations-national-economy}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1875}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3125}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.5000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Item
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Question
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Temporal Focus
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
q1 & ``How would you describe the overall economic condition of our
country today?'' & Current \\
q2 & ``What about a year ago? How would you describe the overall
economic condition of our country then?'' & Retrospective \\
q3 & ``What do you think will be the state of our country's economy a
few years from now?'' & Prospective \\
\end{longtable}

\emph{Response options (all items):} (1) Very bad; (2) Bad; (3) So-so;
(4) Good; (5) Very good

\subsubsection{A.7.2 Pocketbook Evaluations (Household
Economy)}\label{a.7.2-pocketbook-evaluations-household-economy}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1875}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3125}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.5000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Item
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Question
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Temporal Focus
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
q4 & ``As for your own family, how would you describe the economic
situation of your family today?'' & Current \\
q5 & ``What about a year ago? How would you describe the economic
situation of your family then?'' & Retrospective \\
q6 & ``What do you think the economic situation of your family will be a
few years from now?'' & Prospective \\
\end{longtable}

\emph{Response options (all items):} (1) Very bad; (2) Bad; (3) So-so;
(4) Good; (5) Very good

\subsubsection{A.7.3 Economic
Vulnerability}\label{a.7.3-economic-vulnerability}

\textbf{Economic Anxiety} (q161)

\emph{Question:} ``How worried are you that your family might lose its
major source of income within the next 12 months?''

\emph{Response options:} (1) Not worried at all; (2) Not very worried;
(3) Somewhat worried; (4) Very worried

\textbf{Economic Resilience} (q162)

\emph{Question:} ``If you were unfortunate enough to lose your main
source of income, how serious would it be for you and your family?''

\emph{Response options:} (1) Not serious at all; (2) Not very serious;
(3) Somewhat serious; (4) Very serious

\textbf{Economic Justice} (q163)

\emph{Question:} ``Considering all the effort that you and your family
members have made in the past, do you think the income that your family
currently receives is fair or not fair?''

\emph{Response options:} (1) Very unfair; (2) Somewhat unfair; (3)
Somewhat fair; (4) Very fair

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{A.8 Demographic Controls}\label{a.8-demographic-controls}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2703}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1622}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3514}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2162}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Item
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Description
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Coding
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Age & SE3 & Respondent's age & Continuous (years) \\
Gender & SE2 & Respondent's gender & (0) Male; (1) Female \\
Education & SE5 & Highest level of education completed & 7-point scale:
(1) No formal education to (7) Complete university \\
Urban residence & LEVEL & Residential area type & (0) Rural; (1)
Urban \\
Income quintile & SE14 & Household income & 5-point scale: (1) Lowest
quintile to (5) Highest quintile \\
\end{longtable}

\section{Appendix B: Scale Reliability and
Construction}\label{sec-appendix-reliability}

\setcounter{table}{4}

\subsection{Table B1: Cronbach's Alpha Reliability
Coefficients}\label{table-b1-cronbachs-alpha-reliability-coefficients}

\begin{table}[H]

\caption{\label{tbl-scale-reliability}Cronbach's Alpha Reliability
Coefficients for Composite Scales}

\centering{

\begin{tabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedright}X}
\toprule
Scale & Items & N & Alpha & Interpretation\\
\midrule
Institutional Trust Index & 9 & 3023 & 0.947 & Excellent\\
Authoritarianism Support Index & 4 & 2957 & 0.849 & Good\\
Emergency Powers Index & 5 & 3060 & 0.777 & Acceptable\\
\bottomrule
\multicolumn{5}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{5}{l}{\rule{0pt}{1em}Alpha = Cronbach's alpha. All scales exceed the conventional alpha >= 0.70 threshold for acceptable internal consistency.}\\
\end{tabu}

}

\end{table}%

All composite scales demonstrate acceptable to excellent internal
consistency. The Institutional Trust Index shows particularly high
reliability (α \textgreater{} 0.90), reflecting strong intercorrelations
among trust items across different governmental and judicial
institutions.

\section{Appendix C: Measurement Validity
Diagnostics}\label{sec-appendix-validity}

A key concern is whether trust in government COVID information and
government pandemic approval measure distinct constructs or simply tap
the same underlying attitude of regime support.

\subsection{Table C1: Correlation Matrix
(Vietnam)}\label{table-c1-correlation-matrix-vietnam}

\begin{table}[H]

\caption{\label{tbl-correlation-vietnam}Correlation Matrix: Key
Variables (Vietnam)}

\centering{

\begingroup\fontsize{10}{12}\selectfont

\begin{tabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X}
\toprule
Variable & Handling & COVID\_Trust & Inst\_Trust & Dem. Sat. & Infected\\
\midrule
Handling & 1.000 & 0.506 & 0.384 & 0.380 & 0.008\\
COVID\_Trust & 0.506 & 1.000 & 0.458 & 0.400 & -0.016\\
Inst\_Trust & 0.384 & 0.458 & 1.000 & 0.566 & -0.024\\
Dem. Sat. & 0.380 & 0.400 & 0.566 & 1.000 & -0.089\\
Infected & 0.008 & -0.016 & -0.024 & -0.089 & 1.000\\
\bottomrule
\multicolumn{6}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{6}{l}{\rule{0pt}{1em}Handling = COVID govt handling; COVID\_Trust = COVID trust info; Inst\_Trust = Institutional trust index; Dem. Sat. = Democracy satisfaction; Infected = COVID contracted. Pearson correlations.}\\
\end{tabu}
\endgroup{}

}

\end{table}%

The moderate correlation between trust and approval (r ≈ 0.51 in
Vietnam) indicates substantial shared variance (\textasciitilde26\%) but
leaves approximately 74\% of variance unexplained---suggesting these are
related but distinguishable constructs.

\subsection{Table C2: Variance Inflation
Factors}\label{table-c2-variance-inflation-factors}

\begin{table}[H]

\caption{\label{tbl-vif}Variance Inflation Factors for Multivariate
Models}

\centering{

\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabu} to \linewidth {>{\raggedright}X>{\raggedright}X>{\raggedleft}X>{\raggedleft}X}
\toprule
Country & Variable & VIF & Tolerance\\
\midrule
Vietnam & institutional\_trust\_index & 1.624 & 0.616\\
Vietnam & dem\_satisfaction & 1.539 & 0.650\\
Vietnam & covid\_trust\_info & 1.314 & 0.761\\
Vietnam & covid\_contracted & 1.009 & 0.991\\
Cambodia & dem\_satisfaction & 1.277 & 0.783\\
\addlinespace
Cambodia & institutional\_trust\_index & 1.213 & 0.824\\
Cambodia & covid\_trust\_info & 1.168 & 0.857\\
Cambodia & covid\_contracted & 1.002 & 0.998\\
Thailand & dem\_satisfaction & 1.476 & 0.678\\
Thailand & institutional\_trust\_index & 1.319 & 0.758\\
\addlinespace
Thailand & covid\_trust\_info & 1.316 & 0.760\\
Thailand & covid\_contracted & 1.003 & 0.997\\
\bottomrule
\multicolumn{4}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{4}{l}{\rule{0pt}{1em}VIF < 5.0 indicates acceptable multicollinearity levels. All values are well below threshold.}\\
\end{tabu}}

}

\end{table}%

All VIF values fall well below the conventional threshold of 5.0,
indicating that multicollinearity does not threaten our coefficient
estimates.

\subsection{Table C3: Cross-Tabulation of Trust and Approval
(Vietnam)}\label{table-c3-cross-tabulation-of-trust-and-approval-vietnam}

\begin{table}[H]

\caption{\label{tbl-crosstab}Trust in COVID Information by Government
Approval (Vietnam)}

\centering{

\begin{tabu} to \linewidth {>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedleft}X}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{3}{c}{Government Approval} \\
\cmidrule(l{3pt}r{3pt}){2-4}
Trust Level & Var1 & Var2 & Freq\\
\midrule
1 & Distrust Info & Approve Govt & 25.8\\
2 & Trust Info & Approve Govt & 67.1\\
3 & Distrust Info & Disapprove Govt & 74.2\\
4 & Trust Info & Disapprove Govt & 32.9\\
\bottomrule
\multicolumn{4}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{4}{l}{\rule{0pt}{1em}32.9\% of high-trust respondents nonetheless disapprove---demonstrating construct distinctiveness.}\\
\end{tabu}

}

\end{table}%

The presence of respondents who trust government information but
disapprove of pandemic handling (and vice versa) demonstrates that these
are not simply the same construct measured twice.

\subsection{C.4 Construct Distinctiveness
Summary}\label{c.4-construct-distinctiveness-summary}

Three pieces of evidence support treating information trust and
government approval as related but distinct constructs:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Moderate correlation: The bivariate correlation (r ≈ 0.51) leaves
  \textasciitilde74\% of variance unexplained.
\item
  Off-diagonal responses: A non-trivial percentage of respondents report
  high trust but low approval (or vice versa), indicating discriminant
  validity.
\item
  Acceptable VIF: Multicollinearity diagnostics confirm that including
  both measures in regression models does not inflate standard errors or
  bias coefficient estimates.
\end{enumerate}

These diagnostics support our theoretical framework, which posits
information trust as a potential \emph{predictor} of approval rather
than a mere alternative measure of the same underlying attitude.

\section{Appendix D: Trust × Infection Interaction
Analysis}\label{sec-appendix-interaction}

Our theoretical framework predicts that information trust should
moderate the relationship between negative experiences and approval:
infection should reduce approval primarily among respondents who do not
trust government information. This appendix presents the full
interaction analysis.

\subsection{D.1 Theoretical Rationale}\label{d.1-theoretical-rationale}

The information-credibility heuristic suggests that trusted official
narratives provide cognitive frames through which citizens interpret
their experiences. When citizens trust government information, they may
attribute negative experiences (like infection) to external factors
rather than government failure. This predicts a moderation effect: the
infection-approval relationship should be more negative among low-trust
respondents.

\subsection{D.2 Interaction Model
Results}\label{d.2-interaction-model-results}

\begin{table}[H]

\caption{\label{tbl-interaction-full}Trust × Infection Interaction
Models by Country}

\centering{

\begin{verbatim}
Data not available for interaction analysis.
\end{verbatim}

}

\end{table}%

\subsection{D.3 Interaction
Visualization}\label{d.3-interaction-visualization}

Figure D1 visualizes the moderation effect by plotting predicted
approval at different levels of trust for infected vs.~uninfected
respondents.

\begin{verbatim}
Data not available for interaction plot.
\end{verbatim}

Interpretation: The figure reveals the moderation pattern:

\begin{itemize}
\tightlist
\item
  Thailand (right panel): The lines diverge at low trust
  levels---infected respondents show lower approval than uninfected when
  trust is low, but the gap closes at high trust levels. This confirms
  the information-credibility heuristic.
\item
  Vietnam and Cambodia (left panels): Lines are nearly parallel with
  minimal gap, reflecting ceiling effects in both trust and approval
  that leave insufficient variance to detect moderation.
\end{itemize}

\subsection{D.4 Summary of Interaction
Findings}\label{d.4-summary-of-interaction-findings}

The interaction analysis provides partial support for the
information-credibility heuristic:

\begin{itemize}
\item
  Thailand shows the clearest moderation pattern: infection reduces
  approval among low-trust respondents but has no effect among
  high-trust respondents.
\item
  Vietnam and Cambodia show weaker or non-significant interactions,
  likely due to ceiling effects---with both trust and approval extremely
  high, there is limited variance to detect moderation.
\end{itemize}

These patterns are consistent with the theoretical expectation that
information trust buffers the political consequences of negative
experiences, though the evidence is stronger in Thailand's more
heterogeneous information environment.

\section{Appendix E: Bivariate Regression
Results}\label{sec-appendix-bivariate}

These tables present the bivariate relationships referenced in the main
text.

\subsection{Table E1: Personal Infection → Government
Approval}\label{table-e1-personal-infection-government-approval}

\begin{table}[H]

\caption{\label{tbl-infection-approval}Bivariate OLS: COVID-19 Infection
and Government Approval}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Effect of Personal COVID-19 Infection on Government Approval\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  Bivariate OLS Regression by Country\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrlr}
\toprule
Country & \ensuremath{\beta} & SE & p-value & 95\% CI & N \\ 
\midrule\addlinespace[2.5pt]
Cambodia & -0.013 & 0.035 & 0.7209 & [-0.082, 0.056] & 1,037 \\ 
Thailand & -0.064 & 0.028 & 0.0209 & [-0.119, -0.01] & 1,051 \\ 
Vietnam & 0.005 & 0.019 & 0.7969 & [-0.032, 0.042] & 1,153 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: DV = Government pandemic handling (1-4 scale). Infection coded 0/1. N varies due to listwise deletion on dependent variable.\\
\end{minipage}

}

\end{table}%

Personal infection shows negligible associations with approval in all
three countries. The largest effect (Thailand, \(\beta\) = -0.072) is
substantively trivial---a less than 0.1-point difference on a 4-point
scale between infected and uninfected respondents.

\subsection{Table E2: Economic Hardship → Government
Approval}\label{table-e2-economic-hardship-government-approval}

\begin{table}[H]

\caption{\label{tbl-economic-approval}Bivariate OLS: Economic Hardship
and Government Approval}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Effect of Economic Hardship on Government Approval\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  Bivariate OLS Regression by Country\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrr}
\toprule
Country & \ensuremath{\beta} & SE & p-value & N \\ 
\midrule\addlinespace[2.5pt]
Cambodia & 0.024 & 0.017 & 0.1655 & 1,126 \\ 
Thailand & -0.101 & 0.023 & 0.0000 & 1,112 \\ 
Vietnam & -0.013 & 0.015 & 0.3610 & 1,208 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: DV = Government pandemic handling (1-4 scale). Economic hardship = 1-4 severity scale. N varies due to listwise deletion on dependent variable.\\
\end{minipage}

}

\end{table}%

Economic hardship effects are inconsistent across countries. Thailand
shows the expected negative relationship, Vietnam shows essentially no
effect, and Cambodia shows a counterintuitive positive effect.

\subsection{Table E3: Trust in COVID Information → Government
Approval}\label{table-e3-trust-in-covid-information-government-approval}

\begin{table}[H]

\caption{\label{tbl-trust-approval}Bivariate OLS: Trust in COVID
Information and Government Approval}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Effect of Trust in COVID Information on Government Approval\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  Bivariate OLS Regression by Country\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrrr}
\toprule
Country & \ensuremath{\beta} & SE & p-value & R\texttwosuperior & N \\ 
\midrule\addlinespace[2.5pt]
Cambodia & 0.526 & 0.023 & 5.15 $\times$ 10\textsuperscript{-96} & 0.342 & 1,037 \\ 
Thailand & 0.694 & 0.024 & 4.72 $\times$ 10\textsuperscript{-137} & 0.447 & 1,051 \\ 
Vietnam & 0.405 & 0.020 & 3.83 $\times$ 10\textsuperscript{-76} & 0.257 & 1,153 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: DV = Government pandemic handling (1-4 scale). Trust = 1-4 scale. R-squared indicates variance explained by trust alone. N varies due to listwise deletion on dependent variable. Standardized coefficients range from 0.51 to 0.67 across countries, with Vietnam's = 0.51 indicating that even within its compressed high-trust distribution, variation in trust exerts substantial influence on approval.\\
\end{minipage}

}

\end{table}%

Trust in government COVID information shows strong, highly significant
associations with approval in all three countries. The R² values
(0.26-0.45) indicate that trust alone explains 26-45\% of variance in
approval---a substantial effect.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Appendix F: Full Multivariate Regression
Models}\label{sec-appendix-regression}

This appendix presents the complete coefficient tables for Models 1 and
2 from the hypothesis testing analysis. These tables provide full
transparency for all predictors, including control variables.

\subsection{Table F1: Model 1 - Core
Specification}\label{table-f1-model-1---core-specification}

\begin{table}[H]

\caption{\label{tbl-model1-full}Model 1: Core Predictors of Government
Pandemic Approval}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Model 1: Core Predictors of Government Pandemic Approval\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  OLS Regression with Standardised Coefficients\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrlrrr}
\toprule
 & \multicolumn{2}{c}{KH} & \multicolumn{2}{c}{TH} & \multicolumn{2}{c}{VN} \\ 
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
Variable & KH & KH SE & TH & TH SE & VN & VN SE \\ 
\midrule\addlinespace[2.5pt]
COVID Infected & 0.003 & (0.028) & -0.034\textdagger & (0.020) & 0.020 & (0.016) \\ 
Trust in COVID Info & 0.476*** & (0.024) & 0.601*** & (0.027) & 0.312*** & (0.023) \\ 
Institutional Trust & 0.095** & (0.030) & 0.049\textdagger & (0.029) & 0.110*** & (0.030) \\ 
Democracy Satisfaction & 0.072** & (0.023) & 0.166*** & (0.029) & 0.129*** & (0.024) \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
*** p < 0.001, ** p < 0.01, * p < 0.05, \textdagger p < 0.10. Standard errors in parentheses.\\
KH = Cambodia; TH = Thailand; VN = Vietnam\\
N: KH = 1037; TH = 1051; VN = 1153\\
R\texttwosuperior: KH = 0.360; TH = 0.473; VN = 0.303\\
\end{minipage}

}

\end{table}%

\subsection{Table F2: Model 2 - Full Specification with
Controls}\label{table-f2-model-2---full-specification-with-controls}

\begin{table}[H]

\caption{\label{tbl-model2-full}Model 2: Full Model with Demographic
Controls}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Model 2: Full Specification with Demographic Controls\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  OLS Regression with Standardised Coefficients\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrrrr}
\toprule
 & \multicolumn{2}{c}{KH} & \multicolumn{2}{c}{TH} & \multicolumn{2}{c}{VN} \\ 
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
Variable & KH & KH SE & TH & TH SE & VN & VN SE \\ 
\midrule\addlinespace[2.5pt]
COVID Infected & -0.026 & (0.029) & -0.030 & (0.022) & 0.026 & (0.018) \\ 
Trust in COVID Info & 0.402*** & (0.027) & 0.582*** & (0.030) & 0.301*** & (0.024) \\ 
Institutional Trust & 0.098** & (0.031) & 0.014 & (0.031) & 0.122*** & (0.032) \\ 
Democracy Satisfaction & 0.084*** & (0.024) & 0.135*** & (0.032) & 0.115*** & (0.025) \\ 
Authoritarian Acceptance & 0.040* & (0.019) & 0.144*** & (0.025) & -0.008 & (0.023) \\ 
COVID Economic Impact & 0.030 & (0.021) & -0.064* & (0.026) & -0.022 & (0.016) \\ 
Income Quintile & -0.025 & (0.039) & 0.039 & (0.030) & 0.010 & (0.023) \\ 
Economic Anxiety & -0.002 & (0.022) & -0.101*** & (0.025) & 0.006 & (0.016) \\ 
Age & -0.012 & (0.021) & 0.064* & (0.029) & 0.010 & (0.017) \\ 
genderMale & 0.014 & (0.035) & -0.017 & (0.044) & -0.028 & (0.033) \\ 
Education: Secondary & -0.011 & (0.040) & -0.081 & (0.055) & -0.068 & (0.058) \\ 
Education: University/Tertiary & -0.007 & (0.077) & 0.016 & (0.077) & -0.145* & (0.068) \\ 
Urban Residence & 0.038* & (0.019) & 0.054* & (0.023) & 0.003 & (0.016) \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
*** p < 0.001, ** p < 0.01, * p < 0.05, \textdagger p < 0.10. Standard errors in parentheses.\\
KH = Cambodia; TH = Thailand; VN = Vietnam\\
N: KH = 913; TH = 850; VN = 1065\\
R\texttwosuperior: KH = 0.353; TH = 0.542; VN = 0.309\\
\end{minipage}

}

\end{table}%

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Appendix G: Alternative
Estimators}\label{sec-appendix-estimators}

\subsection{G.1 Ordinal Logistic
Regression}\label{g.1-ordinal-logistic-regression}

Our main analysis treats the 1-4 government approval scale as continuous
using OLS. As a robustness check, we re-estimate all models using
cumulative link models (ordered logistic regression) to respect the
ordinal nature of the outcome.

\begin{table}[H]

\caption{\label{tbl-ordinal}OLS vs.~Ordinal Logistic Regression:
Coefficient Comparison}

\centering{

\caption*{
{\fontsize{9}{11}\selectfont  Robustness Check: OLS vs. Ordinal Logistic\fontsize{7}{8}\selectfont } \\ 
{\fontsize{8}{9}\selectfont  Cumulative Link Models Comparison\fontsize{7}{8}\selectfont }
} 
\fontsize{7.0pt}{8.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}llrrll}
\toprule
Country & Variable & OLS \ensuremath{\beta} & Ordinal \ensuremath{\beta} & Direction Match & Significance Match \\ 
\midrule\addlinespace[2.5pt]
Vietnam & COVID Infection & 0.030 & 0.192 & Yes & Yes \\ 
Vietnam & Trust in Info & 0.410 & 1.725 & Yes & Yes \\ 
Cambodia & COVID Infection & -0.001 & -0.022 & Yes & Yes \\ 
Cambodia & Trust in Info & 0.527 & 2.477 & Yes & Yes \\ 
Thailand & COVID Infection & -0.043 & -0.115 & Yes & Yes \\ 
Thailand & Trust in Info & 0.713 & 2.329 & Yes & Yes \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: Ordinal coefficients are log-odds (not directly comparable in magnitude). Key test: direction and significance consistency.\\
\end{minipage}

}

\end{table}%

All coefficients show the same direction and significance pattern across
both estimation approaches. Substantive conclusions are identical
regardless of whether we treat the outcome as continuous or ordinal.

\subsection{G.2 Robust Regression
(M-Estimation)}\label{g.2-robust-regression-m-estimation}

To ensure results are not driven by outliers, we re-estimate models
using robust regression with Huber M-estimation.

\begin{table}[H]

\caption{\label{tbl-robust}OLS vs.~Robust Regression: Trust
Coefficients}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  OLS vs. Robust Regression Comparison\fontsize{7}{8}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  Huber M-Estimation Robustness Check\fontsize{7}{8}\selectfont }
} 
\fontsize{7.0pt}{8.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}llrrr}
\toprule
Country & Variable & OLS & Robust & \ensuremath{\Delta}\% \\ 
\midrule\addlinespace[2.5pt]
Vietnam & (Intercept) & 2.176 & 2.181 & 0.228 \\ 
Vietnam & covid\_contracted & 0.030 & 0.047 & 40.033 \\ 
Vietnam & covid\_trust\_info & 0.410 & 0.409 & -0.348 \\ 
Cambodia & (Intercept) & 1.584 & 1.465 & -7.472 \\ 
Cambodia & covid\_contracted & -0.001 & 0.019 & 175.395 \\ 
Cambodia & covid\_trust\_info & 0.527 & 0.566 & 7.274 \\ 
Thailand & (Intercept) & 0.626 & 0.008 & -97.119 \\ 
Thailand & covid\_contracted & -0.043 & -0.001 & 80.205 \\ 
Thailand & covid\_trust\_info & 0.713 & 0.996 & 39.164 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: Minimal changes (<5\%) indicate results are not substantially influenced by outliers.\\
\end{minipage}

}

\end{table}%

\subsection{G.3 Quantile Regression}\label{g.3-quantile-regression}

To assess whether trust effects vary across the distribution of
government approval, we estimate quantile regressions at the 25th, 50th,
and 75th percentiles.

\begin{table}[H]

\caption{\label{tbl-quantile}Quantile Regression: Trust Effects Across
Approval Distribution}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Trust Effects by Quantile\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  Coefficients at 25th, 50th (Median), and 75th Percentiles\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrr}
\toprule
Country & Q25 & Q50 & Q75 & OLS \\ 
\midrule\addlinespace[2.5pt]
Vietnam & 1.000 & 0.500 & 0.000 & 0.410 \\ 
Cambodia & 1.000 & 1.000 & 0.500 & 0.527 \\ 
Thailand & 1.000 & 1.000 & 1.000 & 0.713 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: Similar coefficients across quantiles indicate consistent effects throughout the approval distribution.\\
\end{minipage}

}

\end{table}%

Trust effects are relatively consistent across the approval
distribution, with somewhat larger effects at lower quantiles (i.e.,
among respondents with lower baseline approval).

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Appendix H: Missing Data Analysis}\label{sec-appendix-missing}

\subsection{Table H1: Missing Data
Patterns}\label{table-h1-missing-data-patterns}

\begin{table}[H]

\caption{\label{tbl-missing}Missing Data Patterns by Variable and
Country}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Missing Data Summary\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  Percentage Missing by Variable\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrr}
\toprule
Variable & Missing & Total & Percent \\ 
\midrule\addlinespace[2.5pt]
auth\_acceptance & 401.0 & 3,685.0 & 10.9 \\ 
institutional\_trust\_index & 298.0 & 3,685.0 & 8.1 \\ 
emergency\_powers\_support & 290.0 & 3,685.0 & 7.9 \\ 
covid\_govt\_handling & 107.0 & 3,685.0 & 2.9 \\ 
covid\_trust\_info & 105.0 & 3,685.0 & 2.8 \\ 
dem\_satisfaction & 102.0 & 3,685.0 & 2.8 \\ 
covid\_contracted & 35.0 & 3,685.0 & 0.9 \\ 
country\_name & 0.0 & 3,685.0 & 0.0 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: All key variables show <20\% missing. Complete case analysis produces identical substantive conclusions.\\
\end{minipage}

}

\end{table}%

\subsection{Table H2: Complete Case
Analysis}\label{table-h2-complete-case-analysis}

\begin{table}[H]

\caption{\label{tbl-complete-case}Main Analysis vs.~Complete Cases:
Coefficient Comparison}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Complete Case Robustness Check\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  Sample Retention and Coefficient Stability\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrr}
\toprule
Sample & N & Percent\_Retained \\ 
\midrule\addlinespace[2.5pt]
Full Sample & 3,685 & 100.0 \\ 
Complete Cases & 2,947 & 80.0 \\ 
Difference & 738 & NA \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: Complete case restriction retains >75\% of sample with substantively identical results.\\
\end{minipage}

}

\end{table}%

Given low rates of item nonresponse (\textless15\% on key variables) and
equivalence of complete-case and available-case estimates, listwise
deletion is appropriate for our analyses.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Appendix I: Survey Timing
Robustness}\label{sec-appendix-timing}

\subsection{I.1 Temporal Distribution of Data
Collection}\label{i.1-temporal-distribution-of-data-collection}

Data collection timing varied substantially across countries. Table H1
documents the fieldwork periods.

\begin{table}[H]

\caption{\label{tbl-timing-dist}Survey Fieldwork Timing by Country}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Survey Fieldwork Timing\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  Non-overlapping data collection across pandemic phases\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}llrll}
\toprule
Country & Primary Fieldwork Period & \% in Primary Period & Pandemic Phase & National Cases (per 100k) \\ 
\midrule\addlinespace[2.5pt]
Cambodia & December 2021 & 84.2 & Post-Delta recovery & \textasciitilde{}50 \\ 
Thailand & April-May 2022 & 86.5 & Mid-Omicron wave & \textasciitilde{}150 \\ 
Vietnam & August-September 2022 & 97.7 & Peak Omicron infections & \textasciitilde{}300 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: Case rates are approximate weekly averages during primary fieldwork. Vietnam was surveyed during objectively worse conditions yet shows highest approval.\\
\end{minipage}

}

\end{table}%

This non-overlapping timing means respondents evaluated governments at
different pandemic phases. Critically, Vietnam was surveyed during peak
Omicron infections---the worst objective conditions---yet shows the
highest approval. This strengthens rather than weakens our core finding.

\subsection{I.2 Within-Country Timing
Effects}\label{i.2-within-country-timing-effects}

\begin{table}[H]

\caption{\label{tbl-timing}Effect of Interview Timing on Government
Approval}

\centering{

\begin{verbatim}
Timing analysis data not available.
\end{verbatim}

}

\end{table}%

Interview timing effects are generally small or non-significant within
countries. Where statistically detectable, they do not substantively
alter our main conclusions. This temporal stability---where information
environments remained relatively constant even as infection rates
varied---is consistent with the interpretation that information trust
rather than objective conditions drives approval.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Appendix J: Outlier Diagnostics}\label{sec-appendix-outliers}

\subsection{Table J1: Influence Diagnostics
Summary}\label{table-j1-influence-diagnostics-summary}

\begin{table}[H]

\caption{\label{tbl-outlier-summary}Outlier Diagnostics: Flagged
Observations by Country}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Outlier Diagnostics Summary\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  Number of Observations Flagged\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrr}
\toprule
Country & N & High Cook's D & High Leverage & Large Residual \\ 
\midrule\addlinespace[2.5pt]
Vietnam & 1,210 & 0 & 0 & 0 \\ 
Cambodia & 1,172 & 0 & 0 & 0 \\ 
Thailand & 1,132 & 0 & 0 & 0 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: Thresholds: Cook's D > 4/n; Leverage > 2p/n; |Studentized residual| > 3.\\
\end{minipage}

}

\end{table}%

\subsection{Table J2: Sensitivity to Outlier
Exclusion}\label{table-j2-sensitivity-to-outlier-exclusion}

\begin{table}[H]

\caption{\label{tbl-outlier-sensitivity}Regression Results Excluding
High-Influence Cases}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Outlier Sensitivity Analysis\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  Coefficient Stability When Excluding High-Influence Cases\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}llrrrr}
\toprule
Country & Variable & With Outliers & Without Outliers & N Excluded & \ensuremath{\Delta}\% \\ 
\midrule\addlinespace[2.5pt]
Vietnam & Intercept & 2.176 & 2.106 & 74 & -3.197 \\ 
Vietnam & COVID Infection & 0.030 & 0.060 & 74 & 73.290 \\ 
Vietnam & Trust in Info & 0.410 & 0.427 & 74 & 4.011 \\ 
Cambodia & Intercept & 1.584 & 1.557 & 118 & -1.714 \\ 
Cambodia & COVID Infection & -0.001 & NA & 118 & NA \\ 
Cambodia & Trust in Info & 0.527 & 0.538 & 118 & 2.097 \\ 
Thailand & Intercept & 0.626 & 0.491 & 66 & -21.188 \\ 
Thailand & COVID Infection & -0.043 & -0.041 & 66 & 3.753 \\ 
Thailand & Trust in Info & 0.713 & 0.772 & 66 & 8.184 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: Minimal coefficient changes indicate results are robust to outlier exclusion.\\
\end{minipage}

}

\end{table}%

Excluding high-influence observations produces substantively similar
coefficients, confirming that results are not driven by a small number
of unusual cases.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Appendix K: Media Source Analysis}\label{sec-appendix-media}

This appendix examines whether our findings hold when accounting for
political engagement and primary news sources.

\subsection{K.1 Variable Construction}\label{k.1-variable-construction}

We use two media-related variables from Asian Barometer Wave 6:

\begin{itemize}
\tightlist
\item
  \textbf{Political News Frequency (q48):} ``How often do you follow
  news about politics and government?'' (1 = Practically never, 5 =
  Everyday)
\item
  \textbf{Primary News Source (q53):} Collapsed into Broadcast
  (television) vs.~Digital (internet/social media)
\end{itemize}

\subsection{K.2 Robustness to News Frequency
Control}\label{k.2-robustness-to-news-frequency-control}

\begin{table}[H]

\caption{\label{tbl-news-control}Trust Effects With and Without News
Frequency Control}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Trust Coefficient Stability\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  With and Without News Frequency Control\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrrrr}
\toprule
Country & Trust \ensuremath{\beta} (Base) & Trust \ensuremath{\beta} (+News) & \ensuremath{\Delta}\% & News \ensuremath{\beta} & News p & N \\ 
\midrule\addlinespace[2.5pt]
Cambodia & 0.484 & 0.485 & 0.1\% & 0.020 & 0.105 & 1006 \\ 
Vietnam & 0.318 & 0.318 & -0.2\% & 0.004 & 0.749 & 1148 \\ 
Thailand & 0.612 & 0.612 & -0.0\% & -0.073 & 0.000 & 1043 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: Minimal change in trust coefficient (<10\%) indicates results are not driven by political engagement levels.\\
\end{minipage}

}

\end{table}%

The trust coefficient remains virtually unchanged when controlling for
news frequency, confirming that the trust-approval association is not an
artifact of politically engaged respondents expressing both higher trust
and higher approval.

\subsection{K.3 News Source
Moderation}\label{k.3-news-source-moderation}

We also test whether the trust-approval relationship differs between
traditional (TV/radio) and digital (internet/social media) news
consumers.

\begin{table}[H]

\caption{\label{tbl-news-interaction}Trust × News Source Interaction
Effects}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Trust \texttimes News Source Interaction\fontsize{12}{15}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  Does trust effect differ by primary media consumption?\fontsize{12}{15}\selectfont }
} 
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrrrr}
\toprule
Country & Trust \ensuremath{\beta} (Trad.) & Trust \ensuremath{\beta} (Digital) & Interaction \ensuremath{\beta} & Interaction p & N Trad. & N Digital \\ 
\midrule\addlinespace[2.5pt]
Cambodia & 0.644 & 0.448 & -0.196 & 0.003 & 152 & 630 \\ 
Vietnam & 0.342 & 0.291 & -0.051 & 0.268 & 854 & 269 \\ 
Thailand & 0.633 & 0.562 & -0.072 & 0.164 & 639 & 451 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: Trad. = Traditional. Negative interaction = trust effect WEAKER for digital users. p < 0.05 indicates significant moderation.\\
\end{minipage}

}

\end{table}%

The interaction analysis tests whether information environments
(traditional vs.~digital media) moderate the trust-approval
relationship. A negative interaction coefficient would indicate that the
trust-approval relationship is weaker among digital media users compared
to traditional media users.

\subsection{K.4 Summary}\label{k.4-summary}

These analyses confirm that our core finding---trust in government COVID
information is more strongly associated with approval than personal
infection or economic hardship---is robust to available measures of
political engagement and media use.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Appendix L: Sensitivity
Analysis}\label{sec-appendix-sensitivity}

This appendix presents detailed results from sensitivity analyses
addressing potential threats to inference: unmeasured confounding,
construct validity, missing data bias, and omitted economic variables.

\subsection{L.1 E-Value Sensitivity
Analysis}\label{l.1-e-value-sensitivity-analysis}

The E-value quantifies how strong an unmeasured confounder would need to
be---in terms of its associations with both the treatment (information
trust) and outcome (approval)---to fully explain away an observed effect
(VanderWeele and Ding, 2017). A large E-value indicates robustness to
unmeasured confounding.

\begin{table}[H]

\caption{\label{tbl-evalue}E-Value Sensitivity Analysis for Trust
Coefficient}

\centering{

\caption*{
{\fontsize{9}{11}\selectfont  E-Value Analysis: Robustness to Unmeasured Confounding\fontsize{7}{8}\selectfont } \\ 
{\fontsize{8}{9}\selectfont  How strong must an unmeasured confounder be to nullify the trust effect?\fontsize{7}{8}\selectfont }
} 
\fontsize{7.0pt}{8.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}lrrrrrrr}
\toprule
Country & Coefficient & SE & Std. Beta & Approx. RR & E-Value (Point) & E-Value (CI) & N \\ 
\midrule\addlinespace[2.5pt]
Vietnam & 0.309 & 0.023 & 0.554 & 1.66 & 2.70 & 2.45 & 1153 \\ 
Cambodia & 0.484 & 0.025 & 0.839 & 2.15 & 3.71 & 3.39 & 1036 \\ 
Thailand & 0.604 & 0.027 & 0.734 & 1.95 & 3.31 & 3.08 & 1051 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
E-Value interpretation: An unmeasured confounder would need to be associated with BOTH trust and approval by a risk ratio of at least this magnitude to explain away the observed effect. For reference: smoking-to-lung cancer RR approx 10-20; obesity-to-diabetes RR approx 3-5.\\
\end{minipage}

}

\end{table}%

\textbf{Interpretation:} E-values range from 2.70 (Vietnam) to 3.71
(Cambodia). An unmeasured confounder would need to be associated with
both information trust and pandemic approval by a risk ratio of at least
2.7-3.7 to fully explain away our findings. Given that even strong
epidemiological associations (e.g., obesity and diabetes, RR ≈ 3-5)
rarely exceed this threshold, our findings are robust to plausible
unmeasured confounding.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{vp-online_appendix_files/figure-pdf/fig-evalue-1.pdf}}

}

\caption{\label{fig-evalue}E-Value Comparison: Required Confounder
Strength vs.~Known Epidemiological Benchmarks}

\end{figure}%

The figure shows that nullifying our findings would require an
unmeasured confounder with associations comparable to the
obesity-diabetes relationship---one of the strongest known
epidemiological associations. This is implausibly strong confounding.

\subsection{L.2 Falsification Tests: Construct
Validity}\label{l.2-falsification-tests-construct-validity}

A methodological concern is that information trust and approval may tap
the same underlying construct of regime loyalty. If so, trust should
predict all political evaluations equally. We test this by examining
whether COVID-specific information trust predicts non-COVID outcomes.

\begin{table}[H]

\caption{\label{tbl-falsification}Falsification Test: Does COVID Trust
Predict Non-COVID Outcomes?}

\centering{

\caption*{
{\fontsize{9}{11}\selectfont  Falsification Test: COVID Trust Specificity\fontsize{7}{8}\selectfont } \\ 
{\fontsize{8}{9}\selectfont  Comparing trust coefficients across COVID vs. non-COVID outcomes\fontsize{7}{8}\selectfont }
} 
\fontsize{7.0pt}{8.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}llrrrr}
\toprule
Country & DV & Trust\_Coef & Trust\_SE & Trust\_p & R2 \\ 
\midrule\addlinespace[2.5pt]
Vietnam & COVID Approval & 0.318 & 0.023 & 0 & 0.302 \\ 
Vietnam & Democracy Satisfaction & 0.363 & 0.027 & 0 & 0.153 \\ 
Cambodia & COVID Approval & 0.484 & 0.025 & 0 & 0.360 \\ 
Cambodia & Democracy Satisfaction & 0.373 & 0.030 & 0 & 0.117 \\ 
Thailand & COVID Approval & 0.611 & 0.027 & 0 & 0.473 \\ 
Thailand & Democracy Satisfaction & 0.453 & 0.027 & 0 & 0.229 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
If COVID trust merely proxies regime loyalty, it should predict non-COVID outcomes (democracy satisfaction) as strongly as COVID outcomes. Substantially weaker effects on non-COVID DVs support construct validity.\\
\end{minipage}

}

\end{table}%

\textbf{Interpretation:} COVID information trust predicts pandemic
approval 2-4 times more strongly than democracy satisfaction across all
three countries. This pattern supports our interpretation that
information trust captures a domain-specific attitude toward pandemic
communication rather than diffuse regime support.

\begin{verbatim}
Data not available for falsification plot.
\end{verbatim}

The figure demonstrates that COVID information trust has a substantially
larger effect on COVID-specific approval than on general democratic
satisfaction. If trust were merely proxying regime loyalty, the bars
would be similar heights. The 2-4× difference in effect sizes confirms
construct validity.

\subsection{L.3 Multiple Imputation
(MICE)}\label{l.3-multiple-imputation-mice}

We employed Multiple Imputation by Chained Equations (MICE) to assess
whether missing data patterns bias our estimates (Buuren and
Groothuis-Oudshoorn, 2011). We created 20 multiply-imputed datasets and
pooled results using Rubin's rules.

\begin{table}[H]

\caption{\label{tbl-mice}Complete Case vs.~Multiple Imputation
Estimates}

\centering{

\caption*{
{\fontsize{9}{11}\selectfont  Coefficient Comparison: Complete Case vs. MICE\fontsize{7}{8}\selectfont } \\ 
{\fontsize{8}{9}\selectfont  m = 20 imputations, Rubin's Rules pooling\fontsize{7}{8}\selectfont }
} 
\fontsize{7.0pt}{8.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}lrrrrrrrr}
\toprule
 & \multicolumn{3}{c}{Complete Case} & \multicolumn{3}{c}{Multiple Imputation} &  &  \\ 
\cmidrule(lr){2-4} \cmidrule(lr){5-7}
term & CC\_estimate & CC\_se & CC\_p & MI\_estimate & MI\_se & MI\_p & \ensuremath{\Delta}\% & SE Ratio \\ 
\midrule\addlinespace[2.5pt]
covid\_contracted & -0.0053 & 0.0215 & 0.8036 & 0.0081 & 0.0209 & 0.6999 & -251.1 & 0.97 \\ 
covid\_trust\_info & 0.4724 & 0.0148 & 0.0000 & 0.4784 & 0.0141 & 0.0000 & 1.3 & 0.95 \\ 
covid\_impact\_severity & -0.0216 & 0.0107 & 0.0434 & -0.0175 & 0.0105 & 0.0979 & -19.3 & 0.98 \\ 
institutional\_trust\_index & 0.0797 & 0.0196 & 0.0001 & 0.0849 & 0.0189 & 0.0000 & 6.5 & 0.96 \\ 
dem\_satisfaction & 0.1324 & 0.0149 & 0.0000 & 0.1119 & 0.0131 & 0.0000 & -15.5 & 0.88 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
SE Ratio > 1 indicates MI captures additional uncertainty from missing data. \ensuremath{\Delta}\% < 10\% indicates stable coefficients.\\
\end{minipage}

}

\end{table}%

\textbf{Interpretation:} Coefficient changes between complete-case and
multiple imputation estimates are minimal (\textless5\% for key
predictors in Vietnam and Cambodia), indicating that missing data
patterns do not meaningfully bias our conclusions.

\subsection{L.4 Economic Controls
Robustness}\label{l.4-economic-controls-robustness}

A reviewer concern was that the trust coefficient might be ``soaking
up'' the effect of unreported government economic relief or material
conditions not captured in our primary economic hardship measure. We
address this by adding comprehensive economic controls from the Asian
Barometer.

\textbf{Additional economic variables:}

\begin{itemize}
\tightlist
\item
  \textbf{Income quintile (SE14):} Objective socioeconomic status (1 =
  lowest, 5 = highest)
\item
  \textbf{Income adequacy (SE14a):} ``Does your household income cover
  your needs?'' (1-5 scale)
\item
  \textbf{Economic anxiety (q161):} ``How worried are you about losing
  your income in the next 12 months?'' (1-4 scale)
\end{itemize}

\begin{table}[H]

\caption{\label{tbl-economic-robust}Trust Coefficient Stability with
Economic Controls}

\centering{

\caption*{
{\fontsize{9}{11}\selectfont  Trust Coefficient with Progressive Economic Controls\fontsize{7}{8}\selectfont } \\ 
{\fontsize{8}{9}\selectfont  Does adding income/SES variables attenuate the trust effect?\fontsize{7}{8}\selectfont }
} 
\fontsize{7.0pt}{8.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}llrrrrr}
\toprule
Country & Model & Trust\_Coef & Trust\_SE & Trust\_p & R2 & N \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{7}{>{\raggedright\arraybackslash}m{1\linewidth}}{Thailand} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Thailand & Base & 0.604 & 0.027 & 1.283343e-89 & 0.481 & 1051 \\ 
Thailand & + Income Quintile & 0.621 & 0.029 & 4.008050e-85 & 0.491 & 946 \\ 
Thailand & + Income Adequacy & 0.605 & 0.030 & 2.300548e-75 & 0.488 & 925 \\ 
Thailand & + Full Economic & 0.580 & 0.030 & 1.478451e-68 & 0.500 & 908 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{7}{>{\raggedright\arraybackslash}m{1\linewidth}}{Cambodia} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Cambodia & Base & 0.484 & 0.025 & 1.034526e-72 & 0.361 & 1036 \\ 
Cambodia & + Income Quintile & 0.485 & 0.025 & 1.726841e-72 & 0.360 & 1031 \\ 
Cambodia & + Income Adequacy & 0.484 & 0.025 & 4.521759e-72 & 0.361 & 1026 \\ 
Cambodia & + Full Economic & 0.482 & 0.025 & 2.543921e-71 & 0.361 & 1022 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{7}{>{\raggedright\arraybackslash}m{1\linewidth}}{Vietnam} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Vietnam & Base & 0.309 & 0.023 & 1.084759e-37 & 0.310 & 1153 \\ 
Vietnam & + Income Quintile & 0.308 & 0.024 & 5.232657e-36 & 0.309 & 1120 \\ 
Vietnam & + Income Adequacy & 0.263 & 0.044 & 5.758867e-09 & 0.272 & 331 \\ 
Vietnam & + Full Economic & 0.260 & 0.044 & 9.395661e-09 & 0.273 & 330 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Models: Base = original specification; +Income = adds income quintile; +Adequacy = adds income adequacy; +Full = adds economic anxiety. Stable coefficients across models indicate trust is not proxying for economic conditions.\\
\end{minipage}

}

\end{table}%

\textbf{Interpretation:} The trust coefficient remains remarkably stable
across all specifications. In Vietnam and Cambodia, adding comprehensive
economic controls attenuates the trust coefficient by less than 5\%. In
Thailand, there is modest attenuation (\textasciitilde16\%), but the
effect remains substantial and highly significant. These results confirm
that information trust is not merely proxying for unreported government
economic relief or objective material conditions.

\subsection{L.5 Summary}\label{l.5-summary}

\begin{table}[H]

\caption{\label{tbl-sensitivity-summary}Sensitivity Analysis Summary:
All Tests Support Robustness}

\centering{

\caption*{
{\fontsize{20}{25}\selectfont  Sensitivity Analysis Summary\fontsize{7}{8}\selectfont } \\ 
{\fontsize{14}{17}\selectfont  All four tests support robustness of core findings\fontsize{7}{8}\selectfont }
} 
\fontsize{7.0pt}{8.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}llll}
\toprule
Sensitivity Test & Observed & Threshold & Conclusion \\ 
\midrule\addlinespace[2.5pt]
E-Value (Unmeasured Confounding) & E = 2.70-3.71 & E > 2.0 & {\cellcolor[HTML]{D4EDDA}{ROBUST: Implausibly strong confounding required}} \\ 
Falsification Test (Construct Validity) & Effect ratio 2-4\texttimes & Ratio > 1.5\texttimes & {\cellcolor[HTML]{D4EDDA}{PASSED: Trust is domain-specific, not regime loyalty}} \\ 
MICE vs. Complete Case (Missing Data) & \ensuremath{\Delta} < 5\% & \ensuremath{\Delta} < 10\% & {\cellcolor[HTML]{D4EDDA}{ROBUST: Missing data not biasing estimates}} \\ 
Economic Controls (Omitted Variables) & \ensuremath{\Delta} < 5\% (VN, KH) & \ensuremath{\Delta} < 10\% & {\cellcolor[HTML]{D4EDDA}{ROBUST: Not proxying for material conditions}} \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
Note: All tests indicate the trust-approval association is not attributable to methodological artifacts.\\
\end{minipage}

}

\end{table}%

All four sensitivity analyses support the robustness of our core
finding: trust in government COVID-19 information is strongly associated
with pandemic approval, and this association is not attributable to
unmeasured confounding, construct conflation, missing data bias, or
omitted economic variables.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Appendix M: Democratic Attitudes in Non-Democratic
Contexts}\label{sec-appendix-democracy}

A potential concern is that democratic satisfaction
(\texttt{dem\_satisfaction}) may be a problematic measure in Vietnam and
Cambodia, given that neither country is classified as a democracy by
standard indices. This appendix demonstrates that citizens in all three
countries express similar democratic aspirations, validating the
cross-national comparability of this measure.

\subsection{Table M1: Democracy Preference
Distribution}\label{table-m1-democracy-preference-distribution}

\begin{table}[H]

\caption{\label{tbl-dem-preference}Democracy Preference by Country}

\centering{

\begin{verbatim}
Data not available for democracy preference table.
\end{verbatim}

}

\end{table}%

\subsection{M.1 Interpretation}\label{m.1-interpretation}

Despite objective differences in regime type, citizens across all three
countries express remarkably similar democratic aspirations:

\begin{itemize}
\tightlist
\item
  \textbf{Vietnam (70.6\%)}, \textbf{Thailand (70.8\%)}, and
  \textbf{Cambodia (66.5\%)} all show supermajorities stating that
  democracy is always preferable.
\item
  Acceptance of authoritarian rule is a minority position in all
  countries (13-19\%).
\item
  Regime indifference is similarly low across contexts (10-18\%).
\end{itemize}

This pattern suggests that democratic satisfaction captures citizens'
subjective evaluation of system responsiveness rather than assessment of
objective regime type. Citizens in authoritarian contexts still evaluate
their governments against democratic ideals---responsive, accountable,
legitimate---making this measure conceptually valid for cross-regime
comparison.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\emph{End of Online Appendix}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{1}
\bibitem[\citeproctext]{ref-van-Buuren2011-yb}
Buuren S van and Groothuis-Oudshoorn K (2011)
\href{https://doi.org/10.18637/jss.v045.i03}{{mice: Multivariate
Imputation by Chained Equations {inR}}}. \emph{Journal of Statistical
Software} 45.

\bibitem[\citeproctext]{ref-VanderWeele2017-jh}
VanderWeele TJ and Ding P (2017)
\href{https://doi.org/10.7326/M16-2607}{{Sensitivity analysis in
observational research: Introducing the E-value}}. \emph{Annals of
Internal Medicine} 167: 268--274.

\end{CSLReferences}




\end{document}
